### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getSelectedText' of undefined

### ISSUE THREAD

**Issue by CirrusThink** [manolenso/zurb-foundation-doc#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [zurb-doc](https://github.com/manolenso/zurb-foundation-doc) package 0.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getSelectedText' of undefined

```
At /Users/dolly/.atom/packages/zurb-doc/lib/zurb-doc.js:15

TypeError: Cannot read property 'getSelectedText' of undefined
    at Object.search (/packages/zurb-doc/lib/zurb-doc.js:15:63)
    at HTMLElement.zurbDocDoc (/packages/zurb-doc/lib/zurb-doc.js:9:36)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1354:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:348:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:15.6.0 tree-view:remove-project-folder (div.header.list-item.project-root-header)
     -0:09.8.0 zurb-doc:doc (div.item-views)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-foundation-6 0.2.0 
atom-zurb-foundation 2.1.0 
foundation5-snippets 0.2.2 
zurb-doc 0.1.0 
```

**Comment by manolenso** [comment]
Atom: 1.21.1 x64
Windows seven
zurb-doc package 0.1.0

You should open a doc in atom and type word like "button" for example Ctrl + Alt + z
